/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mini_monopoly;

/**
 *
 * @author Kenne
 */
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;

public class MiniMonopolyGUI extends javax.swing.JFrame {

    /**
     * Creates new form MiniMonopolyGUI
     */
    public MiniMonopolyGUI() {
        initComponents();
        
        landNameLabels = new javax.swing.JLabel[] {
            landName1,
            landName2,
            landName3,
            landName7,
            landName8,
            landName9
        };

        landPriceLabels = new javax.swing.JLabel[] {
            landPrice1,
            landPrice2,
            landPrice3,
            landPrice7,
            landPrice8,
            landPrice9
        };
        
        replaceLandInfo();
    }
    
    private void replaceLandInfo() {
        JSONArray lands = loadLandsFromJson();
        if (lands == null || lands.size() < 3) {
            System.err.println("Not enough lands in JSON or failed to load");
            return;
        }

        for (int i = 0; i <= 5; i++) { // change number when needed
            try {
                JSONObject land = (JSONObject) lands.get(i);

                String name = (String) land.get("name");
                Number price = (Number) land.get("price");

                landNameLabels[i].setText(name != null ? name : "???");
                landPriceLabels[i].setText(price != null ? "$" + price : "-");
            } catch (Exception e) {
                landNameLabels[i].setText("Error");
                landPriceLabels[i].setText("?");
                e.printStackTrace();
            }
        }
    }

    private JSONArray loadLandsFromJson() {
        try {
            InputStreamReader reader = new InputStreamReader(
                getClass().getResourceAsStream("/resources/board.json"),
                StandardCharsets.UTF_8
            );

            JSONParser parser = new JSONParser();
            JSONArray array = (JSONArray) parser.parse(reader);
            reader.close();
            return array;
        } catch (Exception e) {
            e.printStackTrace();
            System.err.println("Failed to load /resources/board.json");
            return null;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        player1Panel = new javax.swing.JPanel();
        player1Label = new javax.swing.JLabel();
        balanceLabel1 = new javax.swing.JLabel();
        positionLabel1 = new javax.swing.JLabel();
        statusLabel1 = new javax.swing.JLabel();
        colorPanel1 = new javax.swing.JPanel();
        player2Panel = new javax.swing.JPanel();
        player2Label = new javax.swing.JLabel();
        balanceLabel2 = new javax.swing.JLabel();
        positionLabel2 = new javax.swing.JLabel();
        statusLabel2 = new javax.swing.JLabel();
        colorPanel2 = new javax.swing.JPanel();
        player3Panel = new javax.swing.JPanel();
        player3Label = new javax.swing.JLabel();
        balanceLabel3 = new javax.swing.JLabel();
        positionLabel3 = new javax.swing.JLabel();
        statusLabel3 = new javax.swing.JLabel();
        colorPanel3 = new javax.swing.JPanel();
        player4Panel = new javax.swing.JPanel();
        player4Label = new javax.swing.JLabel();
        balanceLabel4 = new javax.swing.JLabel();
        positionLabel4 = new javax.swing.JLabel();
        statusLabel4 = new javax.swing.JLabel();
        colorPanel4 = new javax.swing.JPanel();
        gameBoardPanel = new javax.swing.JPanel();
        slot0 = new javax.swing.JPanel();
        slotNum0 = new javax.swing.JLabel();
        slot1 = new javax.swing.JPanel();
        slotNum1 = new javax.swing.JLabel();
        landName1 = new javax.swing.JLabel();
        landPrice1 = new javax.swing.JLabel();
        ownerColor1 = new javax.swing.JPanel();
        slot2 = new javax.swing.JPanel();
        slotNum2 = new javax.swing.JLabel();
        landName2 = new javax.swing.JLabel();
        landPrice2 = new javax.swing.JLabel();
        ownerColor2 = new javax.swing.JPanel();
        slot3 = new javax.swing.JPanel();
        slotNum3 = new javax.swing.JLabel();
        landName3 = new javax.swing.JLabel();
        landPrice3 = new javax.swing.JLabel();
        ownerColor3 = new javax.swing.JPanel();
        slot4 = new javax.swing.JPanel();
        slotNum4 = new javax.swing.JLabel();
        slot5 = new javax.swing.JPanel();
        slotNum5 = new javax.swing.JLabel();
        slot6 = new javax.swing.JPanel();
        slotNum6 = new javax.swing.JLabel();
        slot7 = new javax.swing.JPanel();
        slotNum7 = new javax.swing.JLabel();
        landName7 = new javax.swing.JLabel();
        landPrice7 = new javax.swing.JLabel();
        ownerColor7 = new javax.swing.JPanel();
        slot8 = new javax.swing.JPanel();
        slotNum8 = new javax.swing.JLabel();
        landName8 = new javax.swing.JLabel();
        landPrice8 = new javax.swing.JLabel();
        ownerColor8 = new javax.swing.JPanel();
        slot9 = new javax.swing.JPanel();
        slotNum9 = new javax.swing.JLabel();
        landName9 = new javax.swing.JLabel();
        landPrice9 = new javax.swing.JLabel();
        ownerColor9 = new javax.swing.JPanel();
        slot10 = new javax.swing.JPanel();
        slotNum10 = new javax.swing.JLabel();
        landName10 = new javax.swing.JLabel();
        landPrice10 = new javax.swing.JLabel();
        ownerColor10 = new javax.swing.JPanel();
        slot11 = new javax.swing.JPanel();
        slotNum11 = new javax.swing.JLabel();
        landName11 = new javax.swing.JLabel();
        landPrice11 = new javax.swing.JLabel();
        ownerColor11 = new javax.swing.JPanel();
        slot12 = new javax.swing.JPanel();
        slotNum12 = new javax.swing.JLabel();
        landName12 = new javax.swing.JLabel();
        landPrice12 = new javax.swing.JLabel();
        ownerColor12 = new javax.swing.JPanel();
        slot13 = new javax.swing.JPanel();
        slotNum13 = new javax.swing.JLabel();
        landName13 = new javax.swing.JLabel();
        landPrice13 = new javax.swing.JLabel();
        ownerColor13 = new javax.swing.JPanel();
        slot14 = new javax.swing.JPanel();
        slotNum14 = new javax.swing.JLabel();
        landName14 = new javax.swing.JLabel();
        landPrice14 = new javax.swing.JLabel();
        ownerColor14 = new javax.swing.JPanel();
        slot15 = new javax.swing.JPanel();
        slotNum15 = new javax.swing.JLabel();
        slot16 = new javax.swing.JPanel();
        slotNum16 = new javax.swing.JLabel();
        slot17 = new javax.swing.JPanel();
        slotNum17 = new javax.swing.JLabel();
        slot18 = new javax.swing.JPanel();
        slotNum18 = new javax.swing.JLabel();
        slot19 = new javax.swing.JPanel();
        slotNum19 = new javax.swing.JLabel();
        landName15 = new javax.swing.JLabel();
        landPrice15 = new javax.swing.JLabel();
        ownerColor15 = new javax.swing.JPanel();
        slot20 = new javax.swing.JPanel();
        slotNum20 = new javax.swing.JLabel();
        landName16 = new javax.swing.JLabel();
        landPrice16 = new javax.swing.JLabel();
        ownerColor16 = new javax.swing.JPanel();
        actionPanel = new javax.swing.JPanel();
        diceButton = new javax.swing.JButton();
        diceNum = new javax.swing.JLabel();
        buyLandButton = new javax.swing.JButton();
        endTurnButton = new javax.swing.JButton();
        editorButton = new javax.swing.JButton();

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        player1Panel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        player1Label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        player1Label.setText("Player 1");

        balanceLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        balanceLabel1.setText("Balance:");

        positionLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        positionLabel1.setText("Position:");

        statusLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        statusLabel1.setText("Status:");

        colorPanel1.setBackground(new java.awt.Color(255, 102, 102));
        colorPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout colorPanel1Layout = new javax.swing.GroupLayout(colorPanel1);
        colorPanel1.setLayout(colorPanel1Layout);
        colorPanel1Layout.setHorizontalGroup(
            colorPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
        );
        colorPanel1Layout.setVerticalGroup(
            colorPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 29, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout player1PanelLayout = new javax.swing.GroupLayout(player1Panel);
        player1Panel.setLayout(player1PanelLayout);
        player1PanelLayout.setHorizontalGroup(
            player1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(player1PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(player1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(player1PanelLayout.createSequentialGroup()
                        .addGroup(player1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(player1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(balanceLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(colorPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(player1PanelLayout.createSequentialGroup()
                        .addGroup(player1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(positionLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(statusLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        player1PanelLayout.setVerticalGroup(
            player1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(player1PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(player1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(colorPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(player1PanelLayout.createSequentialGroup()
                        .addComponent(player1Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(balanceLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(positionLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        player2Panel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        player2Label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        player2Label.setText("Player 2");

        balanceLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        balanceLabel2.setText("Balance:");

        positionLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        positionLabel2.setText("Position:");

        statusLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        statusLabel2.setText("Status:");

        colorPanel2.setBackground(new java.awt.Color(153, 255, 153));
        colorPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout colorPanel2Layout = new javax.swing.GroupLayout(colorPanel2);
        colorPanel2.setLayout(colorPanel2Layout);
        colorPanel2Layout.setHorizontalGroup(
            colorPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
        );
        colorPanel2Layout.setVerticalGroup(
            colorPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 29, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout player2PanelLayout = new javax.swing.GroupLayout(player2Panel);
        player2Panel.setLayout(player2PanelLayout);
        player2PanelLayout.setHorizontalGroup(
            player2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(player2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(player2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(player2PanelLayout.createSequentialGroup()
                        .addGroup(player2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(player2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(balanceLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(colorPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(player2PanelLayout.createSequentialGroup()
                        .addGroup(player2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(positionLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(statusLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        player2PanelLayout.setVerticalGroup(
            player2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(player2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(player2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(colorPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(player2PanelLayout.createSequentialGroup()
                        .addComponent(player2Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(balanceLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(positionLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        player3Panel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        player3Label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        player3Label.setText("Player 3");

        balanceLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        balanceLabel3.setText("Balance:");

        positionLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        positionLabel3.setText("Position:");

        statusLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        statusLabel3.setText("Status:");

        colorPanel3.setBackground(new java.awt.Color(102, 153, 255));
        colorPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout colorPanel3Layout = new javax.swing.GroupLayout(colorPanel3);
        colorPanel3.setLayout(colorPanel3Layout);
        colorPanel3Layout.setHorizontalGroup(
            colorPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
        );
        colorPanel3Layout.setVerticalGroup(
            colorPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 29, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout player3PanelLayout = new javax.swing.GroupLayout(player3Panel);
        player3Panel.setLayout(player3PanelLayout);
        player3PanelLayout.setHorizontalGroup(
            player3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(player3PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(player3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(player3PanelLayout.createSequentialGroup()
                        .addGroup(player3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(player3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(balanceLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(colorPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(player3PanelLayout.createSequentialGroup()
                        .addGroup(player3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(positionLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(statusLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        player3PanelLayout.setVerticalGroup(
            player3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(player3PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(player3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(colorPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(player3PanelLayout.createSequentialGroup()
                        .addComponent(player3Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(balanceLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(positionLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        player4Panel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        player4Label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        player4Label.setText("Player 4");

        balanceLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        balanceLabel4.setText("Balance:");

        positionLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        positionLabel4.setText("Position:");

        statusLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        statusLabel4.setText("Status:");

        colorPanel4.setBackground(new java.awt.Color(255, 255, 153));
        colorPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout colorPanel4Layout = new javax.swing.GroupLayout(colorPanel4);
        colorPanel4.setLayout(colorPanel4Layout);
        colorPanel4Layout.setHorizontalGroup(
            colorPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
        );
        colorPanel4Layout.setVerticalGroup(
            colorPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 29, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout player4PanelLayout = new javax.swing.GroupLayout(player4Panel);
        player4Panel.setLayout(player4PanelLayout);
        player4PanelLayout.setHorizontalGroup(
            player4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(player4PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(player4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(player4PanelLayout.createSequentialGroup()
                        .addGroup(player4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(player4Label, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(balanceLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addComponent(colorPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(player4PanelLayout.createSequentialGroup()
                        .addGroup(player4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(positionLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(statusLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        player4PanelLayout.setVerticalGroup(
            player4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(player4PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(player4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(colorPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(player4PanelLayout.createSequentialGroup()
                        .addComponent(player4Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(balanceLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(positionLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gameBoardPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        gameBoardPanel.setLayout(null);

        slot0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        slotNum0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slotNum0.setText("0");

        javax.swing.GroupLayout slot0Layout = new javax.swing.GroupLayout(slot0);
        slot0.setLayout(slot0Layout);
        slot0Layout.setHorizontalGroup(
            slot0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(slotNum0, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
        );
        slot0Layout.setVerticalGroup(
            slot0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slot0Layout.createSequentialGroup()
                .addComponent(slotNum0)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        gameBoardPanel.add(slot0);
        slot0.setBounds(8, 2, 75, 117);

        slot1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        slotNum1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slotNum1.setText("1");

        landName1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        landName1.setText("Land 1");

        landPrice1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        landPrice1.setText("$3400");

        ownerColor1.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout ownerColor1Layout = new javax.swing.GroupLayout(ownerColor1);
        ownerColor1.setLayout(ownerColor1Layout);
        ownerColor1Layout.setHorizontalGroup(
            ownerColor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ownerColor1Layout.setVerticalGroup(
            ownerColor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout slot1Layout = new javax.swing.GroupLayout(slot1);
        slot1.setLayout(slot1Layout);
        slot1Layout.setHorizontalGroup(
            slot1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(slotNum1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(landName1, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
            .addComponent(landPrice1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ownerColor1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        slot1Layout.setVerticalGroup(
            slot1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slot1Layout.createSequentialGroup()
                .addComponent(slotNum1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(landName1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(landPrice1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ownerColor1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gameBoardPanel.add(slot1);
        slot1.setBounds(95, 2, 75, 117);

        slot2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        slotNum2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slotNum2.setText("2");

        landName2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        landName2.setText("Land 2");

        landPrice2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        landPrice2.setText("$1800");

        ownerColor2.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout ownerColor2Layout = new javax.swing.GroupLayout(ownerColor2);
        ownerColor2.setLayout(ownerColor2Layout);
        ownerColor2Layout.setHorizontalGroup(
            ownerColor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ownerColor2Layout.setVerticalGroup(
            ownerColor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout slot2Layout = new javax.swing.GroupLayout(slot2);
        slot2.setLayout(slot2Layout);
        slot2Layout.setHorizontalGroup(
            slot2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(slotNum2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(landName2, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
            .addComponent(landPrice2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ownerColor2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        slot2Layout.setVerticalGroup(
            slot2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slot2Layout.createSequentialGroup()
                .addComponent(slotNum2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(landName2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(landPrice2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ownerColor2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gameBoardPanel.add(slot2);
        slot2.setBounds(176, 2, 75, 117);

        slot3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        slotNum3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slotNum3.setText("3");

        landName3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        landName3.setText("Land 3");

        landPrice3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        landPrice3.setText("$1800");

        ownerColor3.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout ownerColor3Layout = new javax.swing.GroupLayout(ownerColor3);
        ownerColor3.setLayout(ownerColor3Layout);
        ownerColor3Layout.setHorizontalGroup(
            ownerColor3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ownerColor3Layout.setVerticalGroup(
            ownerColor3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout slot3Layout = new javax.swing.GroupLayout(slot3);
        slot3.setLayout(slot3Layout);
        slot3Layout.setHorizontalGroup(
            slot3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(slotNum3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(landName3, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
            .addComponent(landPrice3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ownerColor3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        slot3Layout.setVerticalGroup(
            slot3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slot3Layout.createSequentialGroup()
                .addComponent(slotNum3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(landName3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(landPrice3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ownerColor3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gameBoardPanel.add(slot3);
        slot3.setBounds(257, 2, 75, 117);

        slot4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        slotNum4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slotNum4.setText("4");

        javax.swing.GroupLayout slot4Layout = new javax.swing.GroupLayout(slot4);
        slot4.setLayout(slot4Layout);
        slot4Layout.setHorizontalGroup(
            slot4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(slotNum4, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
        );
        slot4Layout.setVerticalGroup(
            slot4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slot4Layout.createSequentialGroup()
                .addComponent(slotNum4)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        gameBoardPanel.add(slot4);
        slot4.setBounds(338, 2, 75, 117);

        slot5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        slotNum5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slotNum5.setText("5");

        javax.swing.GroupLayout slot5Layout = new javax.swing.GroupLayout(slot5);
        slot5.setLayout(slot5Layout);
        slot5Layout.setHorizontalGroup(
            slot5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(slotNum5, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
        );
        slot5Layout.setVerticalGroup(
            slot5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slot5Layout.createSequentialGroup()
                .addComponent(slotNum5)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        gameBoardPanel.add(slot5);
        slot5.setBounds(419, 2, 75, 117);

        slot6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        slotNum6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slotNum6.setText("6");

        javax.swing.GroupLayout slot6Layout = new javax.swing.GroupLayout(slot6);
        slot6.setLayout(slot6Layout);
        slot6Layout.setHorizontalGroup(
            slot6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(slotNum6, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
        );
        slot6Layout.setVerticalGroup(
            slot6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slot6Layout.createSequentialGroup()
                .addComponent(slotNum6)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        gameBoardPanel.add(slot6);
        slot6.setBounds(500, 2, 75, 117);

        slot7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        slotNum7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slotNum7.setText("7");

        landName7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        landName7.setText("Land 3");

        landPrice7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        landPrice7.setText("$1800");

        ownerColor7.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout ownerColor7Layout = new javax.swing.GroupLayout(ownerColor7);
        ownerColor7.setLayout(ownerColor7Layout);
        ownerColor7Layout.setHorizontalGroup(
            ownerColor7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ownerColor7Layout.setVerticalGroup(
            ownerColor7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 49, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout slot7Layout = new javax.swing.GroupLayout(slot7);
        slot7.setLayout(slot7Layout);
        slot7Layout.setHorizontalGroup(
            slot7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(slotNum7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(landName7, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
            .addComponent(landPrice7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ownerColor7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        slot7Layout.setVerticalGroup(
            slot7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slot7Layout.createSequentialGroup()
                .addComponent(slotNum7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(landName7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(landPrice7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ownerColor7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gameBoardPanel.add(slot7);
        slot7.setBounds(581, 2, 80, 117);

        slot8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        slotNum8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slotNum8.setText("8");

        landName8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        landName8.setText("Land 3");

        landPrice8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        landPrice8.setText("$1800");

        ownerColor8.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout ownerColor8Layout = new javax.swing.GroupLayout(ownerColor8);
        ownerColor8.setLayout(ownerColor8Layout);
        ownerColor8Layout.setHorizontalGroup(
            ownerColor8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ownerColor8Layout.setVerticalGroup(
            ownerColor8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout slot8Layout = new javax.swing.GroupLayout(slot8);
        slot8.setLayout(slot8Layout);
        slot8Layout.setHorizontalGroup(
            slot8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(slotNum8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(landName8, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
            .addComponent(landPrice8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ownerColor8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        slot8Layout.setVerticalGroup(
            slot8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slot8Layout.createSequentialGroup()
                .addComponent(slotNum8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(landName8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(landPrice8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ownerColor8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gameBoardPanel.add(slot8);
        slot8.setBounds(667, 2, 81, 117);

        slot9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        slotNum9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slotNum9.setText("9");

        landName9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        landName9.setText("Land 3");

        landPrice9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        landPrice9.setText("$1800");

        ownerColor9.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout ownerColor9Layout = new javax.swing.GroupLayout(ownerColor9);
        ownerColor9.setLayout(ownerColor9Layout);
        ownerColor9Layout.setHorizontalGroup(
            ownerColor9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ownerColor9Layout.setVerticalGroup(
            ownerColor9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout slot9Layout = new javax.swing.GroupLayout(slot9);
        slot9.setLayout(slot9Layout);
        slot9Layout.setHorizontalGroup(
            slot9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(slotNum9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(landName9, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
            .addComponent(landPrice9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ownerColor9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        slot9Layout.setVerticalGroup(
            slot9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slot9Layout.createSequentialGroup()
                .addComponent(slotNum9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(landName9, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(landPrice9, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ownerColor9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gameBoardPanel.add(slot9);
        slot9.setBounds(754, 2, 80, 117);

        slot10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        slotNum10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slotNum10.setText("10");

        landName10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        landName10.setText("Land 3");

        landPrice10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        landPrice10.setText("$1800");

        ownerColor10.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout ownerColor10Layout = new javax.swing.GroupLayout(ownerColor10);
        ownerColor10.setLayout(ownerColor10Layout);
        ownerColor10Layout.setHorizontalGroup(
            ownerColor10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ownerColor10Layout.setVerticalGroup(
            ownerColor10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 49, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout slot10Layout = new javax.swing.GroupLayout(slot10);
        slot10.setLayout(slot10Layout);
        slot10Layout.setHorizontalGroup(
            slot10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(slotNum10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(landName10, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
            .addComponent(landPrice10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ownerColor10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        slot10Layout.setVerticalGroup(
            slot10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slot10Layout.createSequentialGroup()
                .addComponent(slotNum10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(landName10, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(landPrice10, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ownerColor10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gameBoardPanel.add(slot10);
        slot10.setBounds(10, 130, 70, 117);

        slot11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        slotNum11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slotNum11.setText("11");

        landName11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        landName11.setText("Land 3");

        landPrice11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        landPrice11.setText("$1800");

        ownerColor11.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout ownerColor11Layout = new javax.swing.GroupLayout(ownerColor11);
        ownerColor11.setLayout(ownerColor11Layout);
        ownerColor11Layout.setHorizontalGroup(
            ownerColor11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ownerColor11Layout.setVerticalGroup(
            ownerColor11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 49, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout slot11Layout = new javax.swing.GroupLayout(slot11);
        slot11.setLayout(slot11Layout);
        slot11Layout.setHorizontalGroup(
            slot11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(slotNum11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(landName11, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
            .addComponent(landPrice11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ownerColor11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        slot11Layout.setVerticalGroup(
            slot11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slot11Layout.createSequentialGroup()
                .addComponent(slotNum11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(landName11, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(landPrice11, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ownerColor11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gameBoardPanel.add(slot11);
        slot11.setBounds(90, 130, 70, 117);

        slot12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        slotNum12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slotNum12.setText("12");

        landName12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        landName12.setText("Land 3");

        landPrice12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        landPrice12.setText("$1800");

        ownerColor12.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout ownerColor12Layout = new javax.swing.GroupLayout(ownerColor12);
        ownerColor12.setLayout(ownerColor12Layout);
        ownerColor12Layout.setHorizontalGroup(
            ownerColor12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ownerColor12Layout.setVerticalGroup(
            ownerColor12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 49, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout slot12Layout = new javax.swing.GroupLayout(slot12);
        slot12.setLayout(slot12Layout);
        slot12Layout.setHorizontalGroup(
            slot12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(slotNum12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(landName12, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
            .addComponent(landPrice12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ownerColor12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        slot12Layout.setVerticalGroup(
            slot12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slot12Layout.createSequentialGroup()
                .addComponent(slotNum12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(landName12, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(landPrice12, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ownerColor12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gameBoardPanel.add(slot12);
        slot12.setBounds(170, 130, 70, 117);

        slot13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        slotNum13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slotNum13.setText("13");

        landName13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        landName13.setText("Land 3");

        landPrice13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        landPrice13.setText("$1800");

        ownerColor13.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout ownerColor13Layout = new javax.swing.GroupLayout(ownerColor13);
        ownerColor13.setLayout(ownerColor13Layout);
        ownerColor13Layout.setHorizontalGroup(
            ownerColor13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ownerColor13Layout.setVerticalGroup(
            ownerColor13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 49, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout slot13Layout = new javax.swing.GroupLayout(slot13);
        slot13.setLayout(slot13Layout);
        slot13Layout.setHorizontalGroup(
            slot13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(slotNum13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(landName13, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
            .addComponent(landPrice13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ownerColor13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        slot13Layout.setVerticalGroup(
            slot13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slot13Layout.createSequentialGroup()
                .addComponent(slotNum13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(landName13, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(landPrice13, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ownerColor13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gameBoardPanel.add(slot13);
        slot13.setBounds(250, 130, 70, 117);

        slot14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        slotNum14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slotNum14.setText("14");

        landName14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        landName14.setText("Land 3");

        landPrice14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        landPrice14.setText("$1800");

        ownerColor14.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout ownerColor14Layout = new javax.swing.GroupLayout(ownerColor14);
        ownerColor14.setLayout(ownerColor14Layout);
        ownerColor14Layout.setHorizontalGroup(
            ownerColor14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ownerColor14Layout.setVerticalGroup(
            ownerColor14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 49, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout slot14Layout = new javax.swing.GroupLayout(slot14);
        slot14.setLayout(slot14Layout);
        slot14Layout.setHorizontalGroup(
            slot14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(slotNum14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(landName14, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
            .addComponent(landPrice14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ownerColor14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        slot14Layout.setVerticalGroup(
            slot14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slot14Layout.createSequentialGroup()
                .addComponent(slotNum14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(landName14, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(landPrice14, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ownerColor14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gameBoardPanel.add(slot14);
        slot14.setBounds(330, 130, 70, 117);

        slot15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        slotNum15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slotNum15.setText("15");

        javax.swing.GroupLayout slot15Layout = new javax.swing.GroupLayout(slot15);
        slot15.setLayout(slot15Layout);
        slot15Layout.setHorizontalGroup(
            slot15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(slotNum15, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
        );
        slot15Layout.setVerticalGroup(
            slot15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slot15Layout.createSequentialGroup()
                .addComponent(slotNum15)
                .addGap(0, 99, Short.MAX_VALUE))
        );

        gameBoardPanel.add(slot15);
        slot15.setBounds(410, 130, 75, 117);

        slot16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        slotNum16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slotNum16.setText("16");

        javax.swing.GroupLayout slot16Layout = new javax.swing.GroupLayout(slot16);
        slot16.setLayout(slot16Layout);
        slot16Layout.setHorizontalGroup(
            slot16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(slotNum16, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
        );
        slot16Layout.setVerticalGroup(
            slot16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slot16Layout.createSequentialGroup()
                .addComponent(slotNum16)
                .addGap(0, 99, Short.MAX_VALUE))
        );

        gameBoardPanel.add(slot16);
        slot16.setBounds(490, 130, 75, 117);

        slot17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        slotNum17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slotNum17.setText("17");

        javax.swing.GroupLayout slot17Layout = new javax.swing.GroupLayout(slot17);
        slot17.setLayout(slot17Layout);
        slot17Layout.setHorizontalGroup(
            slot17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(slotNum17, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
        );
        slot17Layout.setVerticalGroup(
            slot17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slot17Layout.createSequentialGroup()
                .addComponent(slotNum17)
                .addGap(0, 99, Short.MAX_VALUE))
        );

        gameBoardPanel.add(slot17);
        slot17.setBounds(580, 130, 75, 117);

        slot18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        slotNum18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slotNum18.setText("18");

        javax.swing.GroupLayout slot18Layout = new javax.swing.GroupLayout(slot18);
        slot18.setLayout(slot18Layout);
        slot18Layout.setHorizontalGroup(
            slot18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(slotNum18, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
        );
        slot18Layout.setVerticalGroup(
            slot18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slot18Layout.createSequentialGroup()
                .addComponent(slotNum18)
                .addGap(0, 99, Short.MAX_VALUE))
        );

        gameBoardPanel.add(slot18);
        slot18.setBounds(660, 130, 75, 117);

        slot19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        slotNum19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slotNum19.setText("19");

        landName15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        landName15.setText("Land 3");

        landPrice15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        landPrice15.setText("$1800");

        ownerColor15.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout ownerColor15Layout = new javax.swing.GroupLayout(ownerColor15);
        ownerColor15.setLayout(ownerColor15Layout);
        ownerColor15Layout.setHorizontalGroup(
            ownerColor15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ownerColor15Layout.setVerticalGroup(
            ownerColor15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 49, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout slot19Layout = new javax.swing.GroupLayout(slot19);
        slot19.setLayout(slot19Layout);
        slot19Layout.setHorizontalGroup(
            slot19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(slotNum19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(landName15, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
            .addComponent(landPrice15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ownerColor15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        slot19Layout.setVerticalGroup(
            slot19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slot19Layout.createSequentialGroup()
                .addComponent(slotNum19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(landName15, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(landPrice15, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ownerColor15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gameBoardPanel.add(slot19);
        slot19.setBounds(750, 130, 80, 117);

        slot20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        slotNum20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slotNum20.setText("19");

        landName16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        landName16.setText("Land 3");

        landPrice16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        landPrice16.setText("$1800");

        ownerColor16.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout ownerColor16Layout = new javax.swing.GroupLayout(ownerColor16);
        ownerColor16.setLayout(ownerColor16Layout);
        ownerColor16Layout.setHorizontalGroup(
            ownerColor16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ownerColor16Layout.setVerticalGroup(
            ownerColor16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 49, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout slot20Layout = new javax.swing.GroupLayout(slot20);
        slot20.setLayout(slot20Layout);
        slot20Layout.setHorizontalGroup(
            slot20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(slotNum20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(landName16, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
            .addComponent(landPrice16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ownerColor16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        slot20Layout.setVerticalGroup(
            slot20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slot20Layout.createSequentialGroup()
                .addComponent(slotNum20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(landName16, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(landPrice16, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ownerColor16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gameBoardPanel.add(slot20);
        slot20.setBounds(10, 260, 80, 117);

        actionPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        diceButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        diceButton.setText("Roll Dice");
        diceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diceButtonActionPerformed(evt);
            }
        });

        diceNum.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        diceNum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        diceNum.setText("5");

        buyLandButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buyLandButton.setText("Buy Land");
        buyLandButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyLandButtonActionPerformed(evt);
            }
        });

        endTurnButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        endTurnButton.setText("End Turn");
        endTurnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endTurnButtonActionPerformed(evt);
            }
        });

        editorButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        editorButton.setText("Editor");
        editorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editorButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout actionPanelLayout = new javax.swing.GroupLayout(actionPanel);
        actionPanel.setLayout(actionPanelLayout);
        actionPanelLayout.setHorizontalGroup(
            actionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(actionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(diceNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(diceButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editorButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buyLandButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(endTurnButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        actionPanelLayout.setVerticalGroup(
            actionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(diceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(diceNum, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buyLandButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(endTurnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 256, Short.MAX_VALUE)
                .addComponent(editorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(gameBoardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(actionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(player1Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(player2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(player3Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(player4Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(player4Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(player3Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(player2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(player1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gameBoardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(actionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void diceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diceButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diceButtonActionPerformed

    private void endTurnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endTurnButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_endTurnButtonActionPerformed

    private void editorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editorButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editorButtonActionPerformed

    private void buyLandButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyLandButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buyLandButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MiniMonopolyGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MiniMonopolyGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MiniMonopolyGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MiniMonopolyGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MiniMonopolyGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actionPanel;
    private javax.swing.JLabel balanceLabel1;
    private javax.swing.JLabel balanceLabel2;
    private javax.swing.JLabel balanceLabel3;
    private javax.swing.JLabel balanceLabel4;
    private javax.swing.JButton buyLandButton;
    private javax.swing.JPanel colorPanel1;
    private javax.swing.JPanel colorPanel2;
    private javax.swing.JPanel colorPanel3;
    private javax.swing.JPanel colorPanel4;
    private javax.swing.JButton diceButton;
    private javax.swing.JLabel diceNum;
    private javax.swing.JButton editorButton;
    private javax.swing.JButton endTurnButton;
    private javax.swing.JPanel gameBoardPanel;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel landName1;
    private javax.swing.JLabel landName10;
    private javax.swing.JLabel landName11;
    private javax.swing.JLabel landName12;
    private javax.swing.JLabel landName13;
    private javax.swing.JLabel landName14;
    private javax.swing.JLabel landName15;
    private javax.swing.JLabel landName16;
    private javax.swing.JLabel landName2;
    private javax.swing.JLabel landName3;
    private javax.swing.JLabel landName7;
    private javax.swing.JLabel landName8;
    private javax.swing.JLabel landName9;
    private javax.swing.JLabel landPrice1;
    private javax.swing.JLabel landPrice10;
    private javax.swing.JLabel landPrice11;
    private javax.swing.JLabel landPrice12;
    private javax.swing.JLabel landPrice13;
    private javax.swing.JLabel landPrice14;
    private javax.swing.JLabel landPrice15;
    private javax.swing.JLabel landPrice16;
    private javax.swing.JLabel landPrice2;
    private javax.swing.JLabel landPrice3;
    private javax.swing.JLabel landPrice7;
    private javax.swing.JLabel landPrice8;
    private javax.swing.JLabel landPrice9;
    private javax.swing.JPanel ownerColor1;
    private javax.swing.JPanel ownerColor10;
    private javax.swing.JPanel ownerColor11;
    private javax.swing.JPanel ownerColor12;
    private javax.swing.JPanel ownerColor13;
    private javax.swing.JPanel ownerColor14;
    private javax.swing.JPanel ownerColor15;
    private javax.swing.JPanel ownerColor16;
    private javax.swing.JPanel ownerColor2;
    private javax.swing.JPanel ownerColor3;
    private javax.swing.JPanel ownerColor7;
    private javax.swing.JPanel ownerColor8;
    private javax.swing.JPanel ownerColor9;
    private javax.swing.JLabel player1Label;
    private javax.swing.JPanel player1Panel;
    private javax.swing.JLabel player2Label;
    private javax.swing.JPanel player2Panel;
    private javax.swing.JLabel player3Label;
    private javax.swing.JPanel player3Panel;
    private javax.swing.JLabel player4Label;
    private javax.swing.JPanel player4Panel;
    private javax.swing.JLabel positionLabel1;
    private javax.swing.JLabel positionLabel2;
    private javax.swing.JLabel positionLabel3;
    private javax.swing.JLabel positionLabel4;
    private javax.swing.JPanel slot0;
    private javax.swing.JPanel slot1;
    private javax.swing.JPanel slot10;
    private javax.swing.JPanel slot11;
    private javax.swing.JPanel slot12;
    private javax.swing.JPanel slot13;
    private javax.swing.JPanel slot14;
    private javax.swing.JPanel slot15;
    private javax.swing.JPanel slot16;
    private javax.swing.JPanel slot17;
    private javax.swing.JPanel slot18;
    private javax.swing.JPanel slot19;
    private javax.swing.JPanel slot2;
    private javax.swing.JPanel slot20;
    private javax.swing.JPanel slot3;
    private javax.swing.JPanel slot4;
    private javax.swing.JPanel slot5;
    private javax.swing.JPanel slot6;
    private javax.swing.JPanel slot7;
    private javax.swing.JPanel slot8;
    private javax.swing.JPanel slot9;
    private javax.swing.JLabel slotNum0;
    private javax.swing.JLabel slotNum1;
    private javax.swing.JLabel slotNum10;
    private javax.swing.JLabel slotNum11;
    private javax.swing.JLabel slotNum12;
    private javax.swing.JLabel slotNum13;
    private javax.swing.JLabel slotNum14;
    private javax.swing.JLabel slotNum15;
    private javax.swing.JLabel slotNum16;
    private javax.swing.JLabel slotNum17;
    private javax.swing.JLabel slotNum18;
    private javax.swing.JLabel slotNum19;
    private javax.swing.JLabel slotNum2;
    private javax.swing.JLabel slotNum20;
    private javax.swing.JLabel slotNum3;
    private javax.swing.JLabel slotNum4;
    private javax.swing.JLabel slotNum5;
    private javax.swing.JLabel slotNum6;
    private javax.swing.JLabel slotNum7;
    private javax.swing.JLabel slotNum8;
    private javax.swing.JLabel slotNum9;
    private javax.swing.JLabel statusLabel1;
    private javax.swing.JLabel statusLabel2;
    private javax.swing.JLabel statusLabel3;
    private javax.swing.JLabel statusLabel4;
    // End of variables declaration//GEN-END:variables

    // Add near the other variable declarations (inside the class)
    private final javax.swing.JLabel[] landNameLabels;
    private final javax.swing.JLabel[] landPriceLabels;
}
